using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using DotNetAiCodeHygiene.Core.Sampling;

namespace DotNetAiCodeHygiene.Core;

internal sealed record ReviewSubject(string Identity, string Content, ReviewItem Item, SubjectTicket? SubjectTicket = null, PopulationTicket? PopulationTicket = null);

internal sealed record RuleModuleResult(
    IReadOnlyList<Finding> Findings,
    IReadOnlyList<ReviewSubject> ReviewSubjects,
    IReadOnlyDictionary<string, string> ReviewSourceContents,
    IReadOnlyList<ReviewSubject>? SelectedReviewSubjects = null,
    string ReviewerClass = "implementer")
{
    internal static RuleModuleResult FindingsOnly(IEnumerable<Finding> findings) => new(findings.ToArray(), [], new Dictionary<string, string>());
    internal static RuleModuleResult Empty { get; } = FindingsOnly([]);
}

internal sealed record RuleModuleExecution(Rule Descriptor, RuleModuleResult Result);

internal enum SamplingExecutionBoundary
{
    Commit,
    Discard
}

/// <summary>Lazy services available to production rule modules for this command.</summary>
internal sealed class RuleContext(RepositorySession session, IReadOnlyList<Document> reportingDocuments, SamplingExecutionBoundary samplingBoundary = SamplingExecutionBoundary.Commit, Action? beforeSamplingCommit = null)
{
    private readonly Dictionary<(string RuleId, DocumentId DocumentId), Dictionary<string, int>> occurrenceCounts = [];
    private readonly Lazy<SamplingSession> sampling = new(() => new SamplingSession(session.Root, beforeSamplingCommit), LazyThreadSafetyMode.ExecutionAndPublication);
    private readonly Dictionary<string, double> activityAges = new(StringComparer.Ordinal);

    internal RepositorySession Session { get; } = session;
    internal IReadOnlyList<Document> ReportingDocuments { get; } = reportingDocuments;
    internal string RelativePath(Document document) => document.FilePath is string path ? Session.Relative(path) : document.Name;
    internal string ProjectIdentity(Document document) => ProjectIdentity(document.Project);
    internal string ProjectIdentity(Project project) => project.FilePath is string path ? Session.Relative(path) : project.Name;
    internal double ProjectActivityAge(Document document)
    {
        string identity = ProjectIdentity(document);
        if (activityAges.TryGetValue(identity, out double known)) { return known; }
        bool complete = TryReadEligibleProjectSources(document.Project, out Dictionary<string, string> sources);
        double age = Sampling.ObserveProjectActivity(identity, sources, complete);
        activityAges.Add(identity, age);
        return age;
    }
    internal bool TryReadEligibleProjectSources(Project project, out Dictionary<string, string> sources)
    {
        sources = new(StringComparer.Ordinal);
        foreach (IGrouping<string, Document> group in project.Documents
            .Where(x => x.FilePath is not null && IsSourcePathEligible(x.FilePath))
            .GroupBy(x => Path.GetFullPath(x.FilePath!), StringComparer.OrdinalIgnoreCase))
        {
            try
            {
                string text = Text(group.First()).ToString();
                if (!HasGeneratedHeader(text)) { sources.Add(Session.Relative(group.Key), text); }
            }
            catch (Exception e) when (e is IOException or UnauthorizedAccessException or InvalidOperationException)
            {
                // A failed read makes the source transition incomplete. Keep its
                // previous baseline and total rather than inferring a deletion.
                sources.Clear();
                return false;
            }
        }
        return true;
    }
    internal static bool IsEligibleSourceDocument(Document document)
    {
        if (document.FilePath is not string path || !IsSourcePathEligible(path)) { return false; }
        return !HasGeneratedHeader(document.GetTextAsync().GetAwaiter().GetResult().ToString());
    }
    private static bool IsSourcePathEligible(string path)
    {
        if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) { return false; }
        string[] parts = path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        if (parts.Any(x => x is "bin" or "obj" or ".git" or ".hygiene")) { return false; }
        string file = Path.GetFileName(path);
        if (file.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) || file.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) || file.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)) { return false; }
        return true;
    }
    private static bool HasGeneratedHeader(string text)
    {
        string header = string.Join("\n", text.Split('\n').Take(5));
        return header.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }
    internal SourceText Text(Document document) => Session.GetFact(("source-text", document.Id), () => document.GetTextAsync().GetAwaiter().GetResult());
    internal SyntaxTree Tree(Document document) => Session.GetFact(("syntax-tree", document.Id), () => document.GetSyntaxTreeAsync().GetAwaiter().GetResult() ?? throw new ProductException($"Roslyn did not provide syntax for '{document.FilePath}'."));
    internal SyntaxNode Root(Document document) => Session.GetFact(("syntax-root", document.Id), () => Tree(document).GetRoot());
    internal Compilation Compilation(Document document) => Session.GetCompilation(document.Project);
    internal SemanticModel SemanticModel(Document document) => Session.GetFact(("semantic-model", document.Id), () => Compilation(document).GetSemanticModel(Tree(document)));
    internal DocumentationSubjectFact DocumentationSubjects(Document document) =>
        Session.GetFact(("documentation-subjects", document.Id), () => DocumentationSubjectFact.Create(Root(document), SemanticModel(document)));
    internal Dictionary<string, int> OccurrenceCounts(string ruleId, Document document) =>
        occurrenceCounts.GetValueOrDefault((ruleId, document.Id)) ?? (occurrenceCounts[(ruleId, document.Id)] = new(StringComparer.Ordinal));
    internal ProfileManager ProfileManager => Session.GetFact("profile-manager", () => new ProfileManager(Session.Root));
    internal SamplingSession Sampling => sampling.Value;
    internal bool HasSampling => sampling.IsValueCreated;
    internal void CompleteSampling()
    {
        if (samplingBoundary == SamplingExecutionBoundary.Commit && sampling.IsValueCreated) { sampling.Value.Commit(); }
    }
    internal PreparedSamplingCommit? PrepareSamplingCommit()
    {
        if (samplingBoundary != SamplingExecutionBoundary.Commit || !sampling.IsValueCreated) { return null; }
        return sampling.Value.PrepareCommit();
    }
}

internal interface IRuleModule
{
    public Rule Descriptor { get; }
    public RuleModuleResult Evaluate(RuleContext context);
}

internal interface IFormatRemediationRule
{
    public Document Format(Document document, Compilation compilation);
}

internal interface INormalizeRemediationRule
{
    public Document Normalize(Document document, Compilation compilation);
}

internal interface IEditorConfigProjectionRule
{
    public IReadOnlyList<KeyValuePair<string, string>> EditorConfigEntries { get; }
}

/// <summary>Executes explicitly registered production rules; the host owns materialization and persistence.</summary>
internal sealed class RuleModuleRunner(IReadOnlyList<IRuleModule> modules)
{
    internal IReadOnlyList<RuleModuleExecution> Run(RuleContext context, IReadOnlySet<string> disabled) =>
        modules.Where(module => module.Descriptor.Diagnose && !disabled.Contains(module.Descriptor.Id))
            .Select(module => new RuleModuleExecution(module.Descriptor, module.Evaluate(context))).ToArray();
}

internal static class RuleCatalog
{
    internal static IReadOnlyList<IRuleModule> Modules { get; } =
    [
        new ProfileAnalysisRuleModule(), new ProfileStyleCopRuleModule(), new BracesStyleRuleModule(), new AccessibilityStyleRuleModule(),
        new RoslynFormatRuleModule(), new ThisQualificationRuleModule(), new RedundantQualificationRuleModule(),
        new DocumentationSummaryRequiredRuleModule(), new DocumentationXmlConsistencyRuleModule(), new DocumentationSentenceRuleModule(),
        new SummaryQualityReviewRuleModule(), new SummaryGermanReviewRuleModule(),
        new LongLineReviewRuleModule(), new ControlFlowVisualBlockRuleModule(), new BoringnessReviewRuleModule()
    ];

    internal static Rule[] All { get; } = Modules.Select(module => module.Descriptor with
    {
        FormatRemediate = module is IFormatRemediationRule,
        NormalizeRemediate = module is INormalizeRemediationRule,
        EditorConfigProject = module is IEditorConfigProjectionRule
    }).ToArray();
    internal static Rule Get(string id) => All.Single(rule => rule.Id == id);
    internal static RuleModuleRunner Runner { get; } = new(Modules);
    internal static IReadOnlyList<ISemanticReviewRuleModule> SemanticReviewModules { get; } = Modules.OfType<ISemanticReviewRuleModule>().ToArray();
    internal static SemanticReviewRuleRunner SemanticReviewRunner { get; } = new(SemanticReviewModules);
}
